//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khruphanth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Relation = new HashSet<Relation>();
        }
    
        public int CId { get; set; }
        public string CTName { get; set; }
        public string CEName { get; set; }
        public Nullable<int> CYear { get; set; }
        public string CSDegreeNameTH { get; set; }
        public string CSDegreeNameEN { get; set; }
        public Nullable<int> CSCredit { get; set; }
        public string CSCurriculum { get; set; }
        public string CSGraJob { get; set; }
        public Nullable<int> CsGeneralCategory { get; set; }
        public Nullable<int> CsComputerCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relation> Relation { get; set; }
    }
}
