//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khruphanth.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComCSDBEntities : DbContext
    {
        public ComCSDBEntities()
            : base("name=ComCSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<FStatus> FStatus { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<OldED> OldED { get; set; }
        public virtual DbSet<project_list> project_list { get; set; }
        public virtual DbSet<RefProvince> RefProvince { get; set; }
        public virtual DbSet<Relation> Relation { get; set; }
        public virtual DbSet<SelectedEmployee> SelectedEmployee { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<T_Category> T_Category { get; set; }
        public virtual DbSet<T_Distributor> T_Distributor { get; set; }
        public virtual DbSet<T_DistributorList> T_DistributorList { get; set; }
        public virtual DbSet<T_Khruphanth> T_Khruphanth { get; set; }
        public virtual DbSet<T_Place> T_Place { get; set; }
        public virtual DbSet<T_RequestList> T_RequestList { get; set; }
        public virtual DbSet<T_Requisition> T_Requisition { get; set; }
        public virtual DbSet<T_Stap> T_Stap { get; set; }
        public virtual DbSet<T_Status> T_Status { get; set; }
        public virtual DbSet<T_Type> T_Type { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Title> Title { get; set; }
        public virtual DbSet<type_project> type_project { get; set; }
        public virtual DbSet<View_Distributor> View_Distributor { get; set; }
        public virtual DbSet<View_QRCODE> View_QRCODE { get; set; }
        public virtual DbSet<View_Requisition> View_Requisition { get; set; }
    }
}
