//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khruphanth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.project_list = new HashSet<project_list>();
        }
    
        public string StuId { get; set; }
        public string StuPassword { get; set; }
        public Nullable<int> StuTitle { get; set; }
        public string StuFName { get; set; }
        public string StuLName { get; set; }
        public string StuSex { get; set; }
        public string StuBDate { get; set; }
        public string StuEmail { get; set; }
        public string StuTel { get; set; }
        public string StuHomeNo { get; set; }
        public string StuMoo { get; set; }
        public string StuRoad { get; set; }
        public string StuTambon { get; set; }
        public string StuAmphur { get; set; }
        public Nullable<int> StuProvince_id { get; set; }
        public string StuZipcode { get; set; }
        public byte[] StuPic { get; set; }
        public Nullable<int> StuOldEd { get; set; }
        public Nullable<int> StuStatus { get; set; }
        public string StuTAdviser { get; set; }
        public string StuDName { get; set; }
        public Nullable<int> StuDJob { get; set; }
        public Nullable<int> StuDIncome { get; set; }
        public string StuMName { get; set; }
        public Nullable<int> StuMJob { get; set; }
        public Nullable<int> StuMIncome { get; set; }
        public Nullable<int> StuFStatus { get; set; }
    
        public virtual FStatus FStatus { get; set; }
        public virtual Job Job { get; set; }
        public virtual Job Job1 { get; set; }
        public virtual OldED OldED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_list> project_list { get; set; }
        public virtual RefProvince RefProvince { get; set; }
        public virtual Status Status { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Title Title { get; set; }
    }
}
