//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khruphanth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Distributor
    {
        public string DistributorID { get; set; }
        public string Di_Date { get; set; }
        public string Di_Status { get; set; }
        public string DL_DistributorID { get; set; }
        public string DL_KhruphanthID { get; set; }
        public string RL_NameKP { get; set; }
        public string KhruphanthID { get; set; }
        public Nullable<int> RL_PlaceID { get; set; }
        public string PL_NamePlace { get; set; }
    }
}
